"""
Pydantic schemas for Fertilizer Recommendation service and agent.
Defines input validations, nutrient deficit reports, and conversational response models.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class FertilizerInputSchema(BaseModel):
    """Input features required for fertilizer recommendation."""
    temperature: float = Field(
        26.0,
        ge=-10.0,
        le=60.0,
        description="Ambient temperature in degrees Celsius (°C)."
    )
    humidity: float = Field(
        65.0,
        ge=0.0,
        le=100.0,
        description="Relative air humidity percentage (0-100%)."
    )
    moisture: float = Field(
        40.0,
        ge=0.0,
        le=100.0,
        description="Soil moisture percentage (0-100%)."
    )
    soil_type: str = Field(
        "Loamy",
        description="Soil texture type: Sandy, Loamy, Black, Red, Clayey."
    )
    crop_type: str = Field(
        "Rice",
        description="Target crop being cultivated (e.g. Rice, Maize, Cotton, Wheat, etc.)."
    )
    nitrogen: float = Field(
        ...,
        ge=0.0,
        le=300.0,
        description="Current soil Nitrogen level (kg/ha)."
    )
    potassium: float = Field(
        ...,
        ge=0.0,
        le=300.0,
        description="Current soil Potassium level (kg/ha)."
    )
    phosphorus: float = Field(
        ...,
        ge=0.0,
        le=300.0,
        description="Current soil Phosphorus level (kg/ha)."
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "temperature": 26.0,
                "humidity": 70.0,
                "moisture": 42.0,
                "soil_type": "Loamy",
                "crop_type": "Rice",
                "nitrogen": 18.0,
                "potassium": 50.0,
                "phosphorus": 55.0
            }
        }
    }


class NutrientDeficitReport(BaseModel):
    """Agronomic analysis comparing current soil nutrients against crop requirements."""
    nitrogen_status: str = Field(..., description="Deficient, Optimal, or Surplus.")
    phosphorus_status: str = Field(..., description="Deficient, Optimal, or Surplus.")
    potassium_status: str = Field(..., description="Deficient, Optimal, or Surplus.")
    limiting_nutrient: str = Field(..., description="The most critically deficient nutrient.")


class FertilizerPredictionResponse(BaseModel):
    """Output generated by the Fertilizer Recommendation ML service."""
    recommended_fertilizer: str = Field(..., description="Recommended commercial fertilizer name.")
    confidence: float = Field(..., description="Model prediction confidence score.")
    dosage_kg_per_acre: float = Field(..., description="Recommended dosage in kilograms per acre.")
    application_schedule: str = Field(..., description="Practical stage-wise application instructions.")
    nutrient_report: NutrientDeficitReport = Field(..., description="Detailed nutrient deficit assessment.")
    sustainability_tip: str = Field(..., description="Eco-friendly guidance to prevent soil degradation.")


class FertilizerAgentQueryRequest(BaseModel):
    """Farmer's natural language query payload for the Fertilizer Agent."""
    query: str = Field(
        ...,
        description="Farmer's query regarding fertilizer, crop type, or nutrient deficiency.",
        examples=["My soil has 18 nitrogen, 55 phosphorus, 50 potassium. I am growing Rice in loamy soil. What fertilizer should I use?"]
    )


class FertilizerAgentResponse(BaseModel):
    """Structured response from the Fertilizer Recommendation Agent."""
    status: str = Field(..., description="'success' if recommendation ready, 'needs_clarification' if inputs missing.")
    recommended_fertilizer: Optional[str] = Field(None, description="Recommended fertilizer name.")
    confidence: Optional[float] = Field(None, description="Confidence score.")
    dosage_kg_per_acre: Optional[float] = Field(None, description="Recommended application dosage.")
    application_schedule: Optional[str] = Field(None, description="Application timing guidance.")
    extracted_parameters: Dict[str, Any] = Field(..., description="Extracted soil and crop parameters.")
    missing_parameters: List[str] = Field(default_factory=list, description="Missing required fields.")
    message: str = Field(..., description="Farmer-friendly conversational advice.")
